version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:
  nginx_config:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alyoshasu/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - nginx_config:/code/nginx_default
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/ww/media
    ports:
      - "80:80"
    depends_on:
      - web
