version: '3.8'

volumes:
  postgres_data:
#  fixtures:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alyoshasu/yamdb:v1.0
    restart: always
#    command: bash -c "python manage.py collectstatic --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
#    ports:
#      - "8000:8000"
    volumes:
      - ./fixtures.json:/code/fixtures.json
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx_default/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static/
      - ./media:/var/ww/media/
    depends_on:
      - web
